# Javascript Node CircleCI 2.1 configuration file
#
#
#
version: 2.1
orbs:
  framer: framer/bridge@dev:0.0.12

workflows:
  version: 2.1
  import-components:
    jobs:
      - framer/import-components:
          component-library-package: "ic-snacks"
          dependant-libraries: ""
          framer-project-path: "./"
          color-token-path: "./assets/colors.json"
          icon-path: "./svg"
          filters:
            branches:
              only: master

  determine-dependency-updates:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only: master
    jobs:
      - framer/determine-dependency-updates:
          component-library-package: "ic-snacks"
          dependant-libraries: ""
          framer-project-path: "./"
          color-token-path: "./assets/colors.json"
          icon-path: "./svg"

  build-and-publish:
    jobs:
      - framer/build:
          framer-project-path: "./"
          filters:
            branches:
              only: master
      - framer/publish:
          framer-project-path: "./"
          framer-package-name: "Snacks Design System"
          requires:
            - framer/build
          filters:
            branches:
              only: master
